"""Security utilities — password hashing & JWT token management.

This module extracts password hashing and JWT operations from
``auth_service`` into an independent, reusable core module so that other
parts of the application (e.g. RBAC middleware) can import security
primitives without pulling in the full service layer.

Password verification is **backward-compatible** with the legacy werkzeug
``pbkdf2:sha256`` hashes that were generated by the original Flask
application.  New password hashes use passlib bcrypt.
"""

import re
from datetime import datetime, timedelta, timezone
from typing import Optional

from jose import jwt, JWTError
from passlib.context import CryptContext

from backend.app.core.config import settings

# ── Password Hashing ──────────────────────────────────────────────────────

# CryptContext that verifies both legacy werkzeug pbkdf2:sha256 hashes and
# modern bcrypt hashes.  New hashes are always bcrypt.
_pwd_context = CryptContext(
    schemes=["bcrypt", "pbkdf2_sha256"],
    default="bcrypt",
    deprecated="auto",
)

# Regex to detect legacy werkzeug pbkdf2:sha256 hash format
_WERKZEUG_PBKDF2_RE = re.compile(r"^pbkdf2:sha256:\d+\$.+\$.+$")


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify *plain_password* against *hashed_password*.

    Supports legacy werkzeug hashes (``pbkdf2:sha256``, ``scrypt``) and
    modern bcrypt hashes produced by :func:`get_password_hash`.
    """
    # Try passlib first (bcrypt / pbkdf2_sha256)
    try:
        if _pwd_context.verify(plain_password, hashed_password):
            return True
    except Exception:
        pass

    # Fallback: werkzeug scrypt hashes (format: scrypt:N:r:p$salt$hash)
    if hashed_password.startswith("scrypt:"):
        from werkzeug.security import check_password_hash
        try:
            return check_password_hash(hashed_password, plain_password)
        except Exception:
            return False

    return False


def get_password_hash(password: str) -> str:
    """Return a bcrypt hash of *password*.

    Raises ``ValueError`` if the password does not meet the minimum
    complexity requirements (length ≥ ``PASSWORD_MIN_LENGTH``, at least
    one uppercase letter, one lowercase letter, and one digit).
    """
    _validate_password_policy(password)
    return _pwd_context.hash(password)


def _validate_password_policy(password: str) -> None:
    """Enforce the application password policy.

    - Minimum length: ``settings.PASSWORD_MIN_LENGTH`` (default 8)
    - At least one uppercase letter
    - At least one lowercase letter
    - At least one digit
    """
    min_len = settings.PASSWORD_MIN_LENGTH
    if len(password) < min_len:
        raise ValueError(f"Password must be at least {min_len} characters long")
    if not re.search(r"[A-Z]", password):
        raise ValueError("Password must contain at least one uppercase letter")
    if not re.search(r"[a-z]", password):
        raise ValueError("Password must contain at least one lowercase letter")
    if not re.search(r"\d", password):
        raise ValueError("Password must contain at least one digit")


# ── JWT Token Management ──────────────────────────────────────────────────


def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    """Create a signed JWT access token.

    Args:
        data: Payload to encode (typically ``{"sub": "<user_id>", "role": "<role>"}``).
        expires_delta: Custom expiry duration.  Defaults to
            ``settings.ACCESS_TOKEN_EXPIRE_MINUTES``.

    Returns:
        Encoded JWT string.
    """
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + (
        expires_delta if expires_delta else timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    )
    to_encode.update({"exp": expire, "type": "access"})
    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)


def create_refresh_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    """Create a signed JWT refresh token.

    Args:
        data: Payload to encode (typically ``{"sub": "<user_id>", "role": "<role>"}``).
        expires_delta: Custom expiry duration.  Defaults to
            ``settings.REFRESH_TOKEN_EXPIRE_MINUTES``.

    Returns:
        Encoded JWT string with ``type: "refresh"``.
    """
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + (
        expires_delta if expires_delta else timedelta(minutes=settings.REFRESH_TOKEN_EXPIRE_MINUTES)
    )
    to_encode.update({"exp": expire, "type": "refresh"})
    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)


def decode_token(token: str) -> dict:
    """Decode and verify a JWT token.

    Args:
        token: Encoded JWT string.

    Returns:
        Decoded payload dict.

    Raises:
        JWTError: If the token is invalid or expired.
    """
    return jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])


def is_refresh_token(payload: dict) -> bool:
    """Return ``True`` if *payload* represents a refresh token."""
    return payload.get("type") == "refresh"


def is_access_token(payload: dict) -> bool:
    """Return ``True`` if *payload* represents an access token."""
    return payload.get("type") == "access"
